-- Rumbo Global · esquema para MySQL 5.7+ / MariaDB 10.3+
CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dni VARCHAR(8) NULL UNIQUE,
  email VARCHAR(160) NULL UNIQUE,
  google_sub VARCHAR(64) NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL DEFAULT '',
  apellido VARCHAR(80) NOT NULL DEFAULT '',
  foto_url VARCHAR(300) NULL,
  password_hash VARCHAR(255) NULL,
  activo TINYINT NOT NULL DEFAULT 1,
  intentos_fallidos TINYINT NOT NULL DEFAULT 0,
  bloqueado_hasta DATETIME NULL,
  creado_en DATETIME NOT NULL,
  ultimo_login DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS log_accesos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT UNSIGNED NULL,
  identificador VARCHAR(120) NOT NULL,
  metodo VARCHAR(12) NOT NULL,
  exito TINYINT NOT NULL,
  motivo VARCHAR(120) NULL,
  ip VARCHAR(45) NOT NULL,
  pais VARCHAR(2) NULL,
  user_agent VARCHAR(250) NULL,
  fecha DATETIME NOT NULL,
  INDEX idx_log_ip (ip, fecha), INDEX idx_log_fecha (fecha),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS proyectos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT UNSIGNED NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  estado VARCHAR(40) NOT NULL DEFAULT 'En diagnóstico',
  avance TINYINT NOT NULL DEFAULT 0,
  fecha_inicio VARCHAR(10) NOT NULL,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS consultas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL,
  telefono VARCHAR(30) NULL,
  mensaje TEXT NOT NULL,
  fecha DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(128) PRIMARY KEY,
  data TEXT NOT NULL,
  updated_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
