import sys
sys.path.insert(0, "_build")
from diag import Diagram

O = "03_Diagramas/"


def c1():
    D = Diagram(2320, 900, "ash", "Diagrama complejo 1: Preparación y habilitaciones", "Proyecto ASHAB · Fase 1", lanes=["Cliente (yerbatera)", "Rumbo Global (consultora)", "Organismos y registros (AR)"])
    D.node("n0", 0, 0, "Decisión de exportar yerba mate", "term")
    D.node("n1", 1, 1, "Diagnóstico del cliente y estudio de mercado")
    D.node("n2", 2, 1, "Selección de países: Siria, Líbano, Jordania y EAU")
    D.node("n3", 3, 0, "Adapta producto: marca ASHAB, etiqueta ES/AR y packaging")
    D.node("n4", 4, 2, "Registro de marca y habilitaciones: ARCA, RNE, RNPA, INAL")
    D.node("n5", 5, 2, "¿Laboratorio y certificados aprobados?", "dec")
    D.node("n6", 6, 1, "Producto listo: ficha técnica y muestras", "term")
    D.edge("n0", "r", "n1", "t")
    D.edge("n1", "r", "n2", "l")
    D.edge("n2", "r", "n3", "l")
    D.edge("n2", "b", "n4", "l")
    D.edge("n3", "r", "n4", "t")
    D.edge("n4", "r", "n5", "l")
    x5, y1 = D.pos(5, 1)
    x3, _ = D.pos(3, 1)
    D.edge("n5", "t", "n3", "b", "NO: corregir", via=[(x5, y1 + 60), (x3, y1 + 60)], lpos=-30)
    D.edge("n5", "r", "n6", "b", "SÍ")
    D.save(O + "C1_preparacion_y_habilitaciones.png")


def c2():
    D = Diagram(2860, 900, "ash", "Diagrama complejo 2: Negociación y cierre comercial", "Proyecto ASHAB · Fase 2", lanes=["Rumbo Global (consultora)", "Importador en Medio Oriente", "Banco"], colw=330)
    D.node("n0", 0, 0, "Producto listo: ficha técnica y muestras", "term")
    D.node("n1", 1, 0, "Búsqueda de importadores: ferias (Gulfood), cámaras árabes y contactos")
    D.node("n2", 2, 1, "Recibe muestras y prueba la yerba")
    D.node("n3", 3, 1, "¿Le interesa el producto?", "dec")
    D.node("n4", 3, 0, "Ajusta la oferta o busca otro importador")
    D.node("n5", 4, 1, "Cotización y negociación: precio, Incoterm y plazos")
    D.node("n6", 5, 1, "¿Acepta las condiciones?", "dec")
    D.node("n7", 5, 0, "Renegocia las condiciones")
    D.node("n8", 6, 0, "Contrato de compraventa firmado")
    D.node("n9", 7, 2, "Seña del 50 % acreditada o carta de crédito confirmada")
    D.node("n10", 7, 0, "Orden de producción confirmada", "term")
    D.edge("n0", "r", "n1", "l")
    D.edge("n1", "b", "n2", "l")
    D.edge("n2", "r", "n3", "l")
    D.edge("n3", "t", "n4", "b", "NO")
    D.edge("n4", "l", "n1", "r")
    D.edge("n3", "r", "n5", "l", "SÍ")
    D.edge("n5", "r", "n6", "l")
    D.edge("n6", "t", "n7", "b", "NO")
    D.edge("n7", "l", "n5", "t")
    D.edge("n6", "r", "n8", "b", "SÍ")
    D.edge("n8", "r", "n9", "l")
    D.edge("n9", "t", "n10", "b")
    D.save(O + "C2_negociacion_y_cierre_comercial.png")


def c3():
    D = Diagram(2830, 1250, "ash", "Diagrama complejo 3: Logística, aduana y cobranza", "Proyecto ASHAB · Fase 3",
                lanes=["Cliente (yerbatera)", "Rumbo Global (consultora)", "Aduana y organismos (AR)", "Transporte y seguro", "Importador en destino"],
                colw=290, nodew=245, nodeh=140, lane_h=220)
    D.node("n0", 0, 0, "Produce y embala el pedido")
    D.node("n1", 1, 3, "Booking de contenedor y flete a Buenos Aires")
    D.node("n2", 2, 1, "Documentos: factura, packing list, certificado de origen y sanitario")
    D.node("n3", 3, 2, "Oficializa el permiso de embarque (ARCA)")
    D.node("n4", 4, 2, "¿Documentación conforme?", "dec")
    D.node("n5", 5, 3, "Embarque, B/L y seguro (saldo del 50 % pagado antes o contra B/L)")
    D.node("n6", 6, 3, "Viaje marítimo de 30 a 40 días a Beirut o Jebel Ali")
    x7,y4=D.pos(7,4); D.node("n7", 7, 4, "¿Aprueba aduana y sanidad?", "dec", xy=(x7-35,y4))
    x5_,_y=D.pos(5.6,4); D.node("n9", 6, 4, "Reclamo al seguro y nueva gestión", xy=(x5_,y4))
    x8,_y=D.pos(8,4); D.node("n8", 8, 4, "Recibe la yerba y la lleva por camión a Siria o Jordania", xy=(x8+20,y4))
    D.node("n10", 8, 1, "Cobranza y cierre del embarque", "term")
    D.edge("n0", "r", "n1", "t")
    D.edge("n1", "r", "n2", "l")
    D.edge("n2", "r", "n3", "t")
    D.edge("n3", "r", "n4", "l")
    x4, _ = D.pos(4, 2)
    x2, _ = D.pos(2, 2)
    yb = D.top + 2 * D.lane_h
    D.edge("n4", "t", "n2", "b", "NO: corregir", via=[(x4, yb), (x2, yb)], lpos=-40)
    D.edge("n4", "r", "n5", "t", "SÍ")
    D.edge("n5", "r", "n6", "l")
    D.edge("n6", "r", "n7", "t")
    D.edge("n7", "l", "n9", "r", "NO")
    D.edge("n7", "r", "n8", "l", "SÍ")
    D.edge("n8", "t", "n10", "b")
    D.save(O + "C3_logistica_aduana_y_cobranza.png")


def c4():
    D = Diagram(2920, 1070, "ash", "Diagrama complejo 4: Ingreso con Google y aprobación de la empresa", "Sitio web ASHAB",
                lanes=["Usuario (empresa árabe)", "Servidor PHP", "Google", "Base de datos"], lane_h=230)
    D.node("n0", 0, 0, "Entra al sitio y elige idioma (es, en, ar)", "term")
    D.node("n1", 1, 0, "Toca «Continuar con Google»")
    D.node("n2", 2, 1, "Crea state y nonce y envía al usuario a Google")
    D.node("n3", 3, 2, "El usuario elige su cuenta y autoriza")
    D.node("n4", 4, 1, "¿Firma y email verificados?", "dec")
    D.node("n5", 4, 0, "Mensaje de error y registro del intento fallido")
    D.node("n6", 5, 3, "Crea o actualiza el usuario y guarda el ingreso (IP, país)")
    D.node("n7", 6, 1, "¿Perfil de empresa completo y aprobado?", "dec")
    D.node("n8", 6, 0, "Completa datos de la empresa y espera la aprobación")
    D.node("n9", 7, 0, "El administrador revisa el registro comercial y aprueba")
    D.node("n10", 8, 0, "Ve precios y pide cotización", "term")
    D.edge("n0", "r", "n1", "l")
    D.edge("n1", "b", "n2", "l")
    D.edge("n2", "r", "n3", "t")
    D.edge("n3", "r", "n4", "b")
    D.edge("n4", "t", "n5", "b", "NO")
    D.edge("n5", "l", "n1", "r")
    D.edge("n4", "r", "n6", "t", "SÍ")
    D.edge("n6", "r", "n7", "b")
    D.edge("n7", "t", "n8", "b", "NO")
    D.edge("n8", "r", "n9", "l")
    D.edge("n9", "r", "n10", "l")
    D.edge("n7", "r", "n10", "b", "SÍ")
    D.save(O + "C4_ingreso_google_y_aprobacion.png")


def c6():
    D = Diagram(3100, 900, "ash", "Diagrama complejo 6: Pedido con seña del 50 %", "Cómo se evitan los pedidos sin sentido",
                lanes=["Cliente (importador)", "Rumbo Global y yerbatera", "Banco"], colw=320)
    D.node("n0", 0, 0, "Pide cotización (mínimo 1.000 kg, máximo 3 pedidos abiertos)", "term")
    D.node("n1", 1, 1, "Emite la proforma: precio, total y seña del 50 %")
    D.node("n2", 2, 0, "Revisa la proforma y acepta los términos")
    D.node("n3", 3, 0, "¿Paga la seña antes de 5 días?", "dec")
    D.node("n4", 3, 1, "La proforma vence y el pedido se cancela", "term")
    D.node("n5", 4, 2, "Transferencia internacional o carta de crédito")
    D.node("n6", 5, 0, "Informa la transferencia en el sitio")
    D.node("n7", 6, 1, "¿Seña acreditada en el banco?", "dec")
    D.node("n8", 6, 0, "Corrige o completa el pago")
    D.node("n9", 7, 1, "Confirma el pedido: produce y reserva el contenedor")
    D.node("n10", 8, 1, "Saldo del 50 % antes de cargar o contra B/L: embarque", "term")
    D.edge("n0", "r", "n1", "t")
    D.edge("n1", "r", "n2", "b")
    D.edge("n2", "r", "n3", "l")
    D.edge("n3", "b", "n4", "t", "NO")
    D.edge("n3", "r", "n5", "t", "SÍ")
    D.edge("n5", "r", "n6", "l")
    D.edge("n6", "b", "n7", "l")
    D.edge("n7", "t", "n8", "b", "NO")
    D.edge("n8", "l", "n6", "r")
    D.edge("n7", "r", "n9", "l", "SÍ")
    D.edge("n9", "r", "n10", "l")
    D.save(O + "C6_pedido_con_sena_50.png")


def c5():
    D = Diagram(2400, 900, "rg", "Diagrama complejo 5: Ciclo de trabajo de la consultora", "Rumbo Global Consultores S.A.", nodew=330, nodeh=170, fs=28)
    X = lambda i: 240 + i * 480
    y0, y1 = 300, 640
    D.node("n1", 0, 0, "Contacto y brief del cliente", num=1, xy=(X(0), y0))
    D.node("n2", 0, 0, "Diagnóstico y análisis de mercado", num=2, xy=(X(1), y0))
    D.node("n3", 0, 0, "Propuesta y contrato", num=3, xy=(X(2), y0))
    D.node("n4", 0, 0, "¿El cliente aprueba?", "dec", xy=(X(3), y0))
    D.node("n5", 0, 0, "Planificación: alcance, hitos y presupuesto", num=4, xy=(X(4), y0))
    D.node("n6", 0, 0, "Ejecución del proyecto", num=5, xy=(X(4), y1))
    D.node("n7", 0, 0, "Control: indicadores y reportes", num=6, xy=(X(3), y1))
    D.node("n8", 0, 0, "¿Se cumplen los objetivos?", "dec", xy=(X(2), y1))
    D.node("n9", 0, 0, "Cierre y lecciones aprendidas", num=7, xy=(X(1), y1))
    D.node("n10", 0, 0, "Mejora continua y fidelización", num=8, xy=(X(0), y1))
    D.edge("n1", "r", "n2", "l")
    D.edge("n2", "r", "n3", "l")
    D.edge("n3", "r", "n4", "l")
    D.edge("n4", "r", "n5", "l", "SÍ")
    D.edge("n4", "t", "n2", "t", "NO: ajustar", via=[(X(3), 175), (X(1), 175)], lpos=-15)
    D.edge("n5", "b", "n6", "t")
    D.edge("n6", "l", "n7", "r")
    D.edge("n7", "l", "n8", "r")
    D.edge("n8", "l", "n9", "r", "SÍ")
    D.edge("n8", "b", "n6", "b", "NO: corregir", via=[(X(2), 830), (X(4), 830)], lpos=0)
    D.edge("n9", "l", "n10", "r")
    D.edge("n10", "t", "n1", "b", "Nuevo ciclo")
    D.save(O + "C5_ciclo_de_trabajo_consultora.png")


if __name__ == "__main__":
    for f in (c1, c2, c3, c4, c5, c6):
        f()
    print("complex ok")
