"""Títulos y descripciones de los diagramas (compartido por la presentación y la versión editable)."""
DIAGS = [
    ("simple", "S1_como_funciona_ashab_simple.png", "Cómo funciona ASHAB: simple", "Del pedido con seña del 50 % hasta el mate en las casas de Medio Oriente, en seis pasos."),
    ("simple", "S2_como_se_usa_la_web_simple.png", "Cómo se usa la página web: simple", "Una empresa nueva elige idioma, ingresa con Google, carga los datos de su empresa, espera la aprobación, pide cotización y paga la seña del 50 %."),
    ("simple", "S3_como_trabaja_la_consultora_simple.png", "Cómo trabaja la consultora: simple", "Escuchar, analizar, planificar y ejecutar con control. El detalle de las 8 etapas está en el último diagrama."),
    ("complejo", "C1_preparacion_y_habilitaciones.png", "Detalle 1: preparación y habilitaciones", "La decisión de exportar arranca el diagnóstico y la selección de países. Mientras el cliente adapta producto y marca, se tramitan registros y habilitaciones. Si el laboratorio o los certificados no aprueban, se corrige y se presenta de nuevo."),
    ("complejo", "C2_negociacion_y_cierre_comercial.png", "Detalle 2: negociación y cierre comercial", "Se buscan importadores y se envían muestras. Si no les interesa, se ajusta la oferta. Si acepta las condiciones se firma el contrato y el banco abre la carta de crédito o recibe el pago anticipado: recién ahí se confirma la producción."),
    ("complejo", "C3_logistica_aduana_y_cobranza.png", "Detalle 3: logística, aduana y cobranza", "El cliente produce y la consultora arma los documentos. La aduana oficializa el permiso de embarque; si falta algo, se corrige. Tras el viaje, el importador aprueba o reclama (seguro). Con la aprobación se cobra el saldo y se cierra el embarque."),
    ("complejo", "C4_ingreso_google_y_aprobacion.png", "Detalle 4: ingreso con Google y aprobación de la empresa", "El usuario toca «Continuar con Google». El servidor valida firma, emisor, vencimiento y email verificado; si algo falla, lo registra. Si todo está bien crea o actualiza el usuario y guarda el ingreso. Los precios y pedidos se habilitan cuando la empresa completa sus datos y el administrador la aprueba."),
    ("complejo", "C6_pedido_con_sena_50.png", "Detalle 5: pedido con seña del 50 %", "Después de la cotización se emite una proforma válida por 5 días. Sin la seña acreditada en el banco no se confirma el pedido, no se produce ni se reserva el contenedor. El saldo del 50 % se paga antes de cargar o contra la copia del B/L."),
    ("complejo", "C5_ciclo_de_trabajo_consultora.png", "Detalle 6: ciclo de trabajo de la consultora", "Ocho etapas con dos puntos de control: la aprobación del cliente antes de planificar y la verificación de objetivos antes de cerrar. Al final, la mejora continua abre un nuevo ciclo."),
]

